plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":repository:timer"))
    implementation(project(":repository:metric"))
    implementation(project(":repository:task"))
    implementation(project(":repository:status"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.room.runtime)
    implementation(libs.room.ktx)
    add("ksp", libs.room.compiler)
    testImplementation(libs.room.testing)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    add("ksp", libs.hilt.compiler.androidx)
    add("ksp", libs.hilt.compiler)
    add("ksp", libs.kotlin.jvm.metadata)
    add("kspTest", libs.hilt.compiler)
    add("kspAndroidTest", libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    
    implementation(project.dependencies.platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    testImplementation(project(":repository:timer"))
    testImplementation(project(":repository:metric"))
    testImplementation(project(":repository:task"))
    testImplementation(project(":repository:status"))
    testImplementation(project(":domain:group"))
    testImplementation(project(":feature:comment"))
    testImplementation(project(":core:login"))
    testImplementation(project(":core:profile"))
    testImplementation(project(":feature:location"))
    testImplementation(project(":core:push"))
    testImplementation(project(":core:cart"))
    testImplementation(project(":feature:share"))
    testImplementation(project(":feature:sync"))
    testImplementation(project(":core:user"))
    testImplementation(project(":core:contact"))
    testImplementation(project(":core:checkout"))
    testImplementation(project(":feature:search"))
    testImplementation(project(":feature:network"))
    testImplementation(project(":core:identity"))
    testImplementation(project(":feature:feed"))
    testImplementation(project(":domain:message"))
    testImplementation(project(":domain:setting"))
    testImplementation(project(":domain:account"))
    testImplementation(project(":feature:post"))
    testImplementation(project(":domain:notification"))
    testImplementation(project(":domain:report"))
    testImplementation(project(":domain:session"))

}